services:
  php:
    image: cake/php
    volumes:
      - "./:/app"
    working_dir: /app

  nginx:
    image: nginx
    volumes:
      - ".:/app"
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    depends_on:
      - php